name: flutter_uploader_example
version: 3.0.0-beta.4
description: Demonstrates how to use the flutter_uploader plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.5
  path_provider: ^2.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.0.5
  flutter_local_notifications: ^17.2.1
  flutter_uploader:
    path: ../
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
